"task_repo":
  "username": "postgres"
  "password": "postgres"
  "host": "task-repo"
  "port": 5432
  "dbname": "postgres"
  "sslmode": "disable"

"http_server":
  "host": "todo-list-app"
  "port": 8080
