"task_repo":
  "username": "postgres"
  "password": "postgres"
  "host": "localhost"
  "port": 5432
  "dbname": "todo_list"
  "sslmode": "disable"

"http_server":
  "host": "localhost"
  "port": 8080
